### ISSUE TITLE
Stuck on "Loading content"

### ISSUE THREAD

**Issue by gregcagle** [joeyberkovitz/plex-aaos#10]
Hey Joey - nice work on the app! Much appreciated. I wonder if I'm doing something wrong, though. I've loaded the app, and it sees all of the playlists on my Plex server with no problem. I've got a strong LTE connection and other network related things work well. But every playlist I try gets stuck on "Loading content". How long should it take? I've tried a playlist with 200 songs, and twenty minutes later it has still not completed. Is there something I should be doing besides waiting longer? Thanks!

**Comment by micksmothers** [comment]
Just jumping in here - I've seen the same behavior since yesterday when my grandson was poking around and tried to load a different playlist. When trying to restore the one I wanted to listen to, I was stuck on "Loading content" also. I have not tried clearing local cache or local data yet, but if it is still exhibiting this behavior I'll report back.

**Comment by gregcagle** [comment]
No progress here. I've cleared out the cache and the data, removed and reinstalled the app, and rebooted the infotainment system with no effect. Except one time it actually stopped and said "something bad happened. Please retry". It's on the latest version (11/14 as far as I can tell). Is there something else I should be trying?

**Comment by joeyberkovitz** [comment]
that's pretty much all that can be tried. I'll prioritize this issue as it seems to be a connectivity related bug, although I probably won't have time to look into it for at least a couple weeks. chances are when I improve the overall connection logic, it will self-resolve, or I'll have a better idea as to what's failing.

**Comment by micksmothers** [comment]
Just to update, I've done everything I can think of: clear cache, clear data, even uninstall and then reinstall. I just get never ending "loading content" now, and don't even see the playlists show up. Something must be either persistently cached locally that survives an app removal/reinstall (unlikely), or something on the Plex server side may think that device is still active. Hmm, maybe I'll look at my Plex instance and see if I can "kill" the device from there.

**Comment by joeyberkovitz** [comment]
i'm not sure if the loading has been more frequent lately, but I've definitely seen it although I've always gotten the app into a working state by navigating back to the main page and selecting a different playlist. sometimes selecting the same playlist didn't resolve it, but selecting a different playlist more consistently gets it into a good state.

**Comment by gregcagle** [comment]
OK, no worries. I can run the full Plex app through carplay if needed, but I'd prefer the AAOS native app. No rush. Thanks!

**Comment by micksmothers** [comment]
I tried removing Plex AAOS from the Authorized Devices page on my Plex instance and then reinstalled from the car, still no joy. I'll see if it "heals" after an infotainment reset on the car next chance I get, but I may just need to wait for the next release. Thanks for working on this, your efforts are much appreciated!

**Comment by joeyberkovitz** [comment]
some info posted on #1 - loading is improved a bit with version 0.4.4, although still expected to fail if the app is opened without an internet connection. in those scenarios, if stuck on loading, the solution for now is to just open another media app and return back, although I'll get to adding a retry mechanism when internet is unavailable - usually the case for the first ~30 seconds after car startup.

**Comment by gregcagle** [comment]
Hey Joey – I gave it another try. It looks like a playlist size issue. I can get “short” playlists (less than 100 songs) to load fine. I have one at 233 songs, and it hangs forever.  Thanks, Greg From: Joey BerkovitzSent: Wednesday, December 28, 2022 2:43 PMTo: joeyberkovitz/plex-aaosCc: gregcagle; AuthorSubject: Re: [joeyberkovitz/plex-aaos] Stuck on "Loading content" (Issue #10) some info posted on #1 - loading is improved a bit with version 0.4.4, although still expected to fail if the app is opened without an internet connection. in those scenarios, if stuck on loading, the solution for now is to just open another media app and return back, although I'll get to adding a retry mechanism when internet is unavailable - usually the case for the first ~30 seconds after car startup.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by joeyberkovitz** [comment]
understood, I'll have to try with a larger playlist. the largest one I tried is ~120 songs and it seems to work fine on the latest version. sorry if I wasn't clear, but the improvements are in version 0.4.4 which was just submitted to Google for review, likely to be released over the next couple days, maybe next week.

**Comment by gregcagle** [comment]
Cool, I’ll try it when I see it. I ran some more tests, a 158 song playlist loads immediately, where a 263 song playlist never did load after five minutes. Maybe it’s a 256 song limit (?). Just a thought. Thanks, Greg From: Joey BerkovitzSent: Wednesday, December 28, 2022 3:47 PMTo: joeyberkovitz/plex-aaosCc: gregcagle; AuthorSubject: Re: [joeyberkovitz/plex-aaos] Stuck on "Loading content" (Issue #10) understood, I'll have to try with a larger playlist. the largest one I tried is ~120 songs and it seems to work fine on the latest version. sorry if I wasn't clear, but the improvements are in version 0.4.4 which was just submitted to Google for review, likely to be released over the next couple days, maybe next week.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by joeyberkovitz** [comment]
definitely possible that the API changes with larger playlists or there's some resource limit somewhere. I'll have to put together a large playlist test and see what's going on

**Comment by micksmothers** [comment]
I'll give it a shot next time I drive. BTW, I can load smaller playlists but the ones that wouldn't load were quite large (thousands of tracks).

**Comment by joeyberkovitz** [comment]
got it, thousands of tracks may be stretching things even if there was no breakage in general. I have to see if the media player (ExoPlayer) supports some sort of dynamic playlist loading because I think that even trying to load a large playlist like that would just generally be problematic and slow

**Comment by gregcagle** [comment]
Understood and do not spend extra effort on it unless you really want to. I can live with a 250ish track limit. Thanks! From: Joey BerkovitzSent: Wednesday, December 28, 2022 8:29 PMTo: joeyberkovitz/plex-aaosCc: gregcagle; AuthorSubject: Re: [joeyberkovitz/plex-aaos] Stuck on "Loading content" (Issue #10) got it, thousands of tracks may be stretching things even if there was no breakage in general. I have to see if the media player (ExoPlayer) supports some sort of dynamic playlist loading because I think that even trying to load a large playlist like that would just generally be problematic and slow—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by micksmothers** [comment]
Hi Joey - I'm still not able to load large playlists even though I was able to with the first public release. Just curious if you're still working on this?

**Comment by joeyberkovitz** [comment]
Yes, although I haven't had much time for this project lately, so when I get to it, I can look into it.

**Comment by micksmothers** [comment]
Thanks, no hurry!

**Comment by gregcagle** [comment]
Sounds good, I've been bogged down rebuilding my Plex server anyway :).
________________________________

**Comment by joeyberkovitz** [comment]
Version 0.4.5 will should be available in beta over the next few days (pending review from Google). If you have time, please join the beta, once it's available, here (https://play.google.com/apps/testing/us.berkovitz.plexaaos) and let me know if the new functionality works well.

I tested it on the full library playlist, in my case a few thousand items, and it worked. If all is good, I'll push to production in 1-2 weeks.

If you'd like to try it earlier, feel free to send over your email address, either here or to joey@berkovitz.us, and I can add you to the internal testing group which gets updates immediately.

**Comment by gregcagle** [comment]
Will do – thanks! From: Joey BerkovitzSent: Thursday, April 13, 2023 11:04 AMTo: joeyberkovitz/plex-aaosCc: gregcagle; AuthorSubject: Re: [joeyberkovitz/plex-aaos] Stuck on "Loading content" (Issue #10) Version 0.4.5 will should be available in beta over the next few days (pending review from Google). If you have time, please join the beta, once it's available, here (https://play.google.com/apps/testing/us.berkovitz.plexaaos) and let me know if the new functionality works well.I tested it on the full library playlist, in my case a few thousand items, and it worked. If all is good, I'll push to production in 1-2 weeks.If you'd like to try it earlier, feel free to send over your email address, either here or to ***@***.***, and I can add you to the internal testing group which gets updates immediately.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by joeyberkovitz** [comment]
I'm going to push this change to production over the next few days. Please let me know if I can close this issue or if there are any remaining concerns related to this problem

**Comment by gregcagle** [comment]
Ship it 😊. I was able to load several different 3000+ song playlists with no problem. Good work. From: Joey BerkovitzSent: Tuesday, April 25, 2023 6:13 PMTo: joeyberkovitz/plex-aaosCc: gregcagle; AuthorSubject: Re: [joeyberkovitz/plex-aaos] Stuck on "Loading content" (Issue #10) I'm going to push this change to production over the next few days. Please let me know if I can close this issue or if there are any remaining concerns related to this problem—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by joeyberkovitz** [comment]
Great, closing this issue as fixed by #14 
Rollout to production is pending approval by Google and should occur over the next few days. Feel free to open a new issue if any other problems arise

**Comment by micksmothers** [comment]
@joeyberkovitz - I'll test it also with my massive playlist once I get the update. My small playlists still load, but the big ones were of course broken. It will be an additional datapoint. Thanks for this work!
