### ISSUE TITLE
Can't login. 404 on the URL provided

### ISSUE THREAD

**Issue by dslugPX** [joeyberkovitz/plex-aaos#13]
Just tried to use this today. 

Can't login with user/pass and the link to: https://plex.tv/link:5J9R
is 404. 

They change something? Would LOVE to have my music on a native app.

**Comment by joeyberkovitz** [comment]
To be clear, there are two login options:
- user/password using your plex.tv account and the login button in the app
- PIN code - go to https://plex.tv/link , login to your account there and then enter the 4-character PIN displayed on the screen

It seems like you may have appended the pin to the URL. Let me know if it works as described above.

**Comment by dslugPX** [comment]
I'm so dumb
of coure that's how it works. Not sure why my user/pass didn't work, but link was fine once I stopped trying to add the pin to the URL :)
