### ISSUE TITLE
Not Working error message

### ISSUE THREAD

**Issue by brunoshine** [joeyberkovitz/plex-aaos#15]
hi

just installed on a Volvo c40 and after the login it gets stuck on this screen with the message “Plex AAOS not working”. Any thoughts? Thanks

![IMG_4721](https://github.com/joeyberkovitz/plex-aaos/assets/709567/e389a468-8d90-4d97-9434-fcfe47472246)

**Comment by joeyberkovitz** [comment]
Just to confirm, you have at least one server on the Plex account that's remotely accessible?

**Comment by brunoshine** [comment]
Question: does it only support music or also videos?  The server only exposes videos

**Comment by joeyberkovitz** [comment]
This is strictly a music player as video playback is not permitted by AAOS while driving

**Comment by brunoshine** [comment]
But while stopped is possible right?

**Comment by joeyberkovitz** [comment]
Sure, but that's not the intention for this app
If you wanted to play videos, you should be able to use a browser such as Vivaldi while stopped

**Comment by brunoshine** [comment]
Oh :( it could be a good (and I think) only (rest of the world) alternative to the video apps that are only  available on the US market.

thanks anyway for the help :)
