### ISSUE TITLE
Playback stops when switching to night mode

### ISSUE THREAD

**Issue by evilforces** [joeyberkovitz/plex-aaos#16]
Installation in a Renault Megane e-tech vehicle with Android Automotive. 

The playback stops when the vehicle lights are activated and the multimedia screen goes to night mode. It also happens in the opposite direction, that is, when going from night mode to day mode. 

The other multimedia applications in the vehicle do not have this problem.

**Comment by joeyberkovitz** [comment]
I'll have to look into what event is triggered on night mode

I don't think that Volvo/Polestar have night mode UIs so I've yet to test that scenario

**Comment by evilforces** [comment]
Don't Volvo/Polestar have night mode? So they go with Google Maps in bright white at night? I think that with the size of the screen on the Megane e-Tech it would be almost impossible to drive without being dazzled by the light from it.

The problem where playback stops occurs in my case when the lights turn on automatically when entering a dark place with the vehicle. I have not tested what happens when turning on the lights manually during the day, but I understand that the problem will not occur since the night mode of the screen is not activated when there is enough light in the passenger compartment. It is for this reason that I believe that the problem is derived from some event in the night mode of the screen and not from the vehicle's own lights.

**Comment by joeyberkovitz** [comment]
fix pushed, will have to wait for Google approval, since we're close to the weekend it could take until next week to be approved. I'll let you know once the update is approved, please let me know if resolved when that happens

**Comment by evilforces** [comment]
Wow!!! That was fast!!! 

Thank you so much for the correction. I'll let you know as soon as I can install the update if the problem has been fixed. 

The truth is that it was quite uncomfortable, since when going through a tunnel the music stopped every time. 

Thank you very much for your interest.

**Comment by joeyberkovitz** [comment]
the update should now be available for download

**Comment by evilforces** [comment]
I have updated to the latest version and the problem has been fixed.

Thank you very much for the speed in updating the program.

I hope you will continue to update the program with new features and improvements.

Congratulations on your work.

**Comment by evilforces** [comment]
Solved
