### ISSUE TITLE
Playlist order

### ISSUE THREAD

**Issue by lucascosti** [joeyberkovitz/plex-aaos#17]
👋 Hi! Firstly, thank you so much for developing this! 🙇‍♂️ I have a Volvo XC40 Recharge, and despite it running Android Automotive, it doesn't support Android Auto. Your app fills a very much needed vacuum, so thank you!

My issue: after installing the app in the car and authing via plex.tv/link, the playlist listing order in the app doesn't seem to be in any order that I can recognize. Is there any way to sort the playlists alphabetically, or otherwise?

My preference would be the sorting options similar to the native Plex UI itself, or hopefully at least:

- Alphabetically
- Last played

**Comment by lucascosti** [comment]
> I have to check, but I'm not sure if playing a playlist here would report back to Plex. If not, which I'm assuming is the case, I would either have to find a way to do so, or store playback information locally.
> 
> Sorting alphabetically should be a trivial change.

No worries, I'd be very satisfied with just alphabetical sorting (I can always rename the playlists to have my most-played ones near the top of that order).

Currently I have 47 playlists, so trying to find the one I'm looking for when it seems Plex is returning them seemingly randomly (but maybe they're in the order I originally imported them into Plex?) is quite difficult at the moment. 🙂

**Comment by joeyberkovitz** [comment]
Alphabetical sorting added here: https://github.com/joeyberkovitz/plex-aaos/commit/e97dbe41796c80b13ef2abcf67c74def57a195f0

Deployed as version 0.5.2, will probably be available in 1-2 days depending on Google review time

**Comment by lucascosti** [comment]
🚀 You're awesome @joeyberkovitz! I'd be happy to donate some $ to you if you have a GitHub Sponsors / ko-fi / buymeacoffee, or alternatively send some $ to a charity of your preference?

Thanks heaps! 🙇‍♂️

**Comment by joeyberkovitz** [comment]
update should be live now
I appreciate the offer, but I'm not looking to gain anything from this project

if you have any issues with this update, or would like any additional sorting functionality, please let me know otherwise we can close out this issue

**Comment by lucascosti** [comment]
Updated and working perfectly. 🎉  Thanks once again, @joeyberkovitz!
