### ISSUE TITLE
Can't select user

### ISSUE THREAD

**Issue by CinPoU** [joeyberkovitz/plex-aaos#18]
Hi,

I connect Plex aaos and then I go to the settings, the pannel close quickly and go back to loading content.
I can switch to the right server before it quits. When I go back, I can see the server but the users stay empty, and go back to loading content.

I have only one server, with many users without pin code.
My car is a Renault Mégane 

Thank you for all your work
Best regards

**Comment by joeyberkovitz** [comment]
version 0.5.3 should roll out within the next few days, whenever Google approves it

I'm guessing that maybe your server is older and has some legacy users that don't have associated email addresses/plex accounts? if so, that was likely throwing things off. let me know if resolved

**Comment by joeyberkovitz** [comment]
Update should be available, just checking if this is now resolved?

**Comment by CinPoU** [comment]
Hi!
Well done!
Thank you very much, now I can see some songs in directories 0-100, 101-200 , etc...
I imagine the artists view and album views will come later.
I also have two music library, it seems it only walk through the first one.

Thank you!
